interface Question {
  text: string; // Text of the question
}

  export const Questions: Question[] =  [{text: "Eu estava mais autoconfiante"},
        {text: "Eu apreciava mais o meu trabalho"}, 
        {text:"Eu estava mais sociável (fazia mais ligações, saia mais)"},
        {text:"Eu queria viajar ou viajava mais"},
        {text:"Eu tinha tendência a dirigir mais rápido ou me arriscar mais enquanto dirigia"},
        {text:"Eu gastava mais ou gastava dinheiro demais"},
        {text:"Eu me arriscava mais em minha vida diária (no meu trabalho e/ou outras atividades)"},
        {text:"Eu estava fisicamente mais ativo(a) (caminhada, esporte, etc.)"},
        {text:"Eu planejava mais atividades e projetos"},
        {text:"Eu tinha mais ideias, eu estava mais criativo(a)"},
        {text:"Eu ficava menos tímido(a) ou inibido(a)"},
        {text:"Eu usava roupas/maquiagem mais coloridas e extravagantes"},
        {text:"Eu queria mais encontrar ou de fato me encontrava com mais pessoas"},
        {text:"Eu estava mais interessado(a) em sexo e/ou tinha desejo sexual aumentado"},
        {text:"Eu paquerava mais e/ou estava sexualmente mais ativo(a)"},
        {text:"Eu falava mais"},
        {text:"Eu pensava mais rápido"},
        {text:"Eu fazia mais piadas ou trocadilhos quando falava"},
        {text:"Eu me distraía com mais facilidade"},
        {text:"Eu me envolvia em muitas coisas novas"},
        {text:"Meus pensamentos pulavam de assunto rapidamente"},
        {text:"Eu fazia coisas mais rapidamente e/ou com maior facilidade"},
        {text:"Eu ficava mais impaciente e/ou ficava irritado(a) mais facilmente"},
        {text:"Eu podia ser cansativo(a) ou irritante para os outros"},
        {text:"Eu me envolvia mais em discussões e disputas"},
        {text:"Meu humor estava melhor, mais otimista"},
        {text:"Eu bebia mais café"},
        {text:"Eu fumava mais cigarros"},
        {text:"Eu bebia mais álcool"},
        {text:"Eu usava mais drogas (sedativos, ansiolíticos, estimulantes, entre outros)"}]